Feature/header
FreeNit/Shop-For-Gamers pull request #1
Opened 2022-11-19 13:14 UTC by KateKolos

2022-11-19 14:45 UTC, uaskylight requested changes
Передивися css. Там є декілька кодів які повторюються. І було б не погано ще повидаляти коміти та класи які не використовуються.

2022-11-19 14:45 UTC, uaskylight commented on src/sass/common/_header.scss
> +    background-image: url(/src/images/fons/mobile/background-menu_x2.jpg);
тут має бути дві картинки, під рутину і звичайну

2022-11-19 15:04 UTC, uaskylight commented on src/sass/common/_header.scss
> +    background-image: url(/src/images/fons/mobile/background-menu_x2.jpg);
Потрібно зробити padding для посилання!

2022-11-20 23:13 UTC, uaskylight approved these changes
great work !

2022-11-21 15:19 UTC, FreeNit requested changes
Потрібно оновити значення змінної

2022-11-21 15:19 UTC, FreeNit commented on src/sass/utils/_vars.scss
> +  --third-text-color: ##8d9289;
Потрібно видалити лишній #

2022-11-21 15:27 UTC, FreeNit approved these changes
Well DONE !!!!

2022-11-21 15:30 UTC, KateKolos commented on src/sass/utils/_vars.scss
> +  --third-text-color: ##8d9289;
значення оновлене, зайвий # видалено

2022-11-21 15:31 UTC, KateKolos commented on src/sass/common/_header.scss
> +    background-image: url(/src/images/fons/mobile/background-menu_x2.jpg);
Картинки оновлено під ретину, падінги для розширення зони клікабельності встановлено

2022-11-21 15:37 UTC, merged